// Code generated by gowsdl DO NOT EDIT.

package brokerbintest

import (
	"context"
	"encoding/xml"
	"time"

	"github.com/enthus-golang/gowsdl/soap"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type AuthenticateRequest struct {
	ReqUsername string `xml:"reqUsername" json:"reqUsername"`

	ReqPassword string `xml:"reqPassword" json:"reqPassword"`

	ReqOptions interface{} `xml:"reqOptions" json:"reqOptions"`
}

type AuthenticateResponse struct {
	ResSession string `xml:"resSession" json:"resSession"`
}

type SearchRequest struct {
	ReqPart interface{} `xml:"reqPart" json:"reqPart"`

	ReqOptions interface{} `xml:"reqOptions" json:"reqOptions"`
}

type SearchResponse struct {
	ResParam interface{} `xml:"resParam" json:"resParam"`
}

// Operation wrapper for Authenticate.
type OperationAuthenticateIn struct {
	ReqUsername *string `xml:"reqUsername,omitempty" json:"reqUsername,omitempty"`

	ReqPassword *string `xml:"reqPassword,omitempty" json:"reqPassword,omitempty"`

	ReqOptions *interface{} `xml:"reqOptions,omitempty" json:"reqOptions,omitempty"`
}

// Operation wrapper for Authenticate.
type OperationAuthenticateOut struct {
	ResSession *string `xml:"resSession,omitempty" json:"resSession,omitempty"`
}

// Operation wrapper for Search.
type OperationSearchIn struct {
	ReqPart *interface{} `xml:"reqPart,omitempty" json:"reqPart,omitempty"`

	ReqOptions *interface{} `xml:"reqOptions,omitempty" json:"reqOptions,omitempty"`
}

// Operation wrapper for Search.
type OperationSearchOut struct {
	ResParam *interface{} `xml:"resParam,omitempty" json:"resParam,omitempty"`
}

type HandleSearchPort interface {
	Authenticate(ctx context.Context, request *AuthenticateRequest) (*AuthenticateResponse, error)

	Search(ctx context.Context, request *SearchRequest) (*SearchResponse, error)
}

type handleSearchPort struct {
	client *soap.Client
}

func NewHandleSearchPort(client *soap.Client) HandleSearchPort {
	return &handleSearchPort{
		client: client,
	}
}

func (service *handleSearchPort) Authenticate(ctx context.Context, request *AuthenticateRequest) (*AuthenticateResponse, error) {

	// RPC-style operation: wrap request in operation element

	α := struct {
		M OperationAuthenticateIn `xml:"tns:Authenticate"`
	}{
		OperationAuthenticateIn{

			ReqUsername: &request.ReqUsername,

			ReqPassword: &request.ReqPassword,

			ReqOptions: &request.ReqOptions,
		},
	}

	γ := struct {
		M OperationAuthenticateOut `xml:"AuthenticateResponse"`
	}{}

	err := service.client.CallContext(ctx, "urn:brokerbin#HandleSearch#Authenticate", α, &γ)
	if err != nil {
		return nil, err
	}

	// Convert response wrapper to output type

	if γ.M.ResSession == nil {
		return nil, nil
	}
	result := &AuthenticateResponse{
		ResSession: *γ.M.ResSession,
	}
	return result, nil

}

func (service *handleSearchPort) Search(ctx context.Context, request *SearchRequest) (*SearchResponse, error) {

	// RPC-style operation: wrap request in operation element

	α := struct {
		M OperationSearchIn `xml:"tns:Search"`
	}{
		OperationSearchIn{

			ReqPart: &request.ReqPart,

			ReqOptions: &request.ReqOptions,
		},
	}

	γ := struct {
		M OperationSearchOut `xml:"SearchResponse"`
	}{}

	err := service.client.CallContext(ctx, "urn:brokerbin#HandleSearch#Search", α, &γ)
	if err != nil {
		return nil, err
	}

	// Convert response wrapper to output type

	if γ.M.ResParam == nil {
		return nil, nil
	}
	result := &SearchResponse{
		ResParam: *γ.M.ResParam,
	}
	return result, nil

}
