// Code generated by gowsdl DO NOT EDIT.

package godemo

import (
	"context"
	"encoding/xml"
	"time"

	"github.com/enthus-golang/gowsdl/soap"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type CheckV1 struct {
	XMLName xml.Name `xml:"tns:checkV1"`

	PartnerCountryCode string `xml:"PartnerCountryCode,omitempty" json:"PartnerCountryCode,omitempty"`

	ProjectReferenceNumber *string `xml:"ProjectReferenceNumber,omitempty" json:"ProjectReferenceNumber,omitempty"`

	StockType string `xml:"StockType,omitempty" json:"StockType,omitempty"`

	ShowBundleComponentPrice *string `xml:"ShowBundleComponentPrice,omitempty" json:"ShowBundleComponentPrice,omitempty"`

	ShowScalePrice *string `xml:"ShowScalePrice,omitempty" json:"ShowScalePrice,omitempty"`

	LineItem []*LineItem `xml:"LineItem,omitempty" json:"LineItem,omitempty"`
}

// TargetNamespace returns the target namespace for SOAP envelope configuration
func (t CheckV1) TargetNamespace() string {
	return "http://b2b.also.com/ActWebServices.PriceAvailability"
}

type LineItem struct {
	MaterialNumber *string `xml:"MaterialNumber,omitempty" json:"MaterialNumber,omitempty"`

	Quantity *string `xml:"Quantity,omitempty" json:"Quantity,omitempty"`
}

type CheckV1Response struct {
	XMLName xml.Name `xml:"checkV1Response"`

	ErrorMessage *string `xml:"ErrorMessage,omitempty" json:"ErrorMessage,omitempty"`

	LineItemResults []*LineItemResults `xml:"LineItemResults,omitempty" json:"LineItemResults,omitempty"`
}

// TargetNamespace returns the target namespace for SOAP envelope configuration
func (t CheckV1Response) TargetNamespace() string {
	return "http://b2b.also.com/ActWebServices.PriceAvailability"
}

type LineItemResults struct {
	ProjectReferenceNumber *string `xml:"ProjectReferenceNumber,omitempty" json:"ProjectReferenceNumber,omitempty"`

	CONT_END_DATE *string `xml:"CONT_END_DATE,omitempty" json:"CONT_END_DATE,omitempty"`

	LineNumber *string `xml:"LineNumber,omitempty" json:"LineNumber,omitempty"`

	MaterialNumber *string `xml:"MaterialNumber,omitempty" json:"MaterialNumber,omitempty"`

	MonetaryAmount *string `xml:"MonetaryAmount,omitempty" json:"MonetaryAmount,omitempty"`

	Schedule []*Schedule `xml:"Schedule,omitempty" json:"Schedule,omitempty"`

	BundleComponents []*BundleComponents `xml:"BundleComponents,omitempty" json:"BundleComponents,omitempty"`

	ScalePrices []*ScalePrices `xml:"ScalePrices,omitempty" json:"ScalePrices,omitempty"`
}

type Schedule struct {
	DateStamp *string `xml:"DateStamp,omitempty" json:"DateStamp,omitempty"`

	Quantity *string `xml:"Quantity,omitempty" json:"Quantity,omitempty"`
}

type BundleComponents struct {
	Line *string `xml:"Line,omitempty" json:"Line,omitempty"`

	ComponentMaterialNumber *string `xml:"ComponentMaterialNumber,omitempty" json:"ComponentMaterialNumber,omitempty"`

	ComponentPrice *string `xml:"ComponentPrice,omitempty" json:"ComponentPrice,omitempty"`
}

type ScalePrices struct {
	Quantity *string `xml:"Quantity,omitempty" json:"Quantity,omitempty"`

	ScalePrice *string `xml:"ScalePrice,omitempty" json:"ScalePrice,omitempty"`
}

type WsCheckV1_PortType interface {
	CheckV1(ctx context.Context, request *CheckV1) (*CheckV1Response, error)
}

type wsCheckV1_PortType struct {
	client *soap.Client
}

func NewWsCheckV1_PortType(client *soap.Client) WsCheckV1_PortType {
	return &wsCheckV1_PortType{
		client: client,
	}
}

func (service *wsCheckV1_PortType) CheckV1(ctx context.Context, request *CheckV1) (*CheckV1Response, error) {
	response := new(CheckV1Response)
	err := service.client.CallContext(ctx, "ActWebServices_PriceAvailability_wsCheckV1_Binder_checkV1", request, response)
	if err != nil {
		return nil, err
	}
	return response, nil
}
