// Code generated by gowsdl DO NOT EDIT.

package godemo

import (
	"context"
	"encoding/xml"
	"github.com/enthus-golang/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type DatabaseEntry struct {
}

type ArrayOfDatabaseEntry struct {
	Item []*DatabaseEntry `xml:"item,omitempty" json:"item,omitempty"`
}

type BedirectServerSearchResult struct {
}

type BedirectServerInformationResult struct {
}

type SearchIn struct {
	KID string `xml:"KID" json:"KID"`

	IDSTRING string `xml:"IDSTRING" json:"IDSTRING"`

	FIRMENNAME_GESAMT string `xml:"FIRMENNAME_GESAMT" json:"FIRMENNAME_GESAMT"`

	ORT string `xml:"ORT" json:"ORT"`

	PLZ string `xml:"PLZ" json:"PLZ"`

	STRASSE_GESAMT string `xml:"STRASSE_GESAMT" json:"STRASSE_GESAMT"`

	TELEFON_VORWAHL string `xml:"TELEFON_VORWAHL" json:"TELEFON_VORWAHL"`

	TELEFON_RUFNUMMER string `xml:"TELEFON_RUFNUMMER" json:"TELEFON_RUFNUMMER"`

	EMAIL string `xml:"EMAIL" json:"EMAIL"`

	URL string `xml:"URL" json:"URL"`

	VERSION string `xml:"VERSION" json:"VERSION"`

	HR_NUMMER string `xml:"HR_NUMMER" json:"HR_NUMMER"`

	HR_ORT string `xml:"HR_ORT" json:"HR_ORT"`

	HR_TYP string `xml:"HR_TYP" json:"HR_TYP"`

	CRF string `xml:"CRF" json:"CRF"`

	ZCRF string `xml:"ZCRF" json:"ZCRF"`

	RECHTSFORM_BD_TEXT string `xml:"RECHTSFORM_BD_TEXT" json:"RECHTSFORM_BD_TEXT"`

	PRIMAERBRANCHE string `xml:"PRIMAERBRANCHE" json:"PRIMAERBRANCHE"`

	SEKUNDAERBRANCHE string `xml:"SEKUNDAERBRANCHE" json:"SEKUNDAERBRANCHE"`

	MARKENBRANCHE string `xml:"MARKENBRANCHE" json:"MARKENBRANCHE"`

	PERSON string `xml:"PERSON" json:"PERSON"`

	ID string `xml:"ID" json:"ID"`

	UMSATZSTEUER_ID string `xml:"UMSATZSTEUER_ID" json:"UMSATZSTEUER_ID"`

	STEUERNUMMER string `xml:"STEUERNUMMER" json:"STEUERNUMMER"`

	STEUERNUMMER_ELSTER string `xml:"STEUERNUMMER_ELSTER" json:"STEUERNUMMER_ELSTER"`

	HANDELSNAME string `xml:"HANDELSNAME" json:"HANDELSNAME"`

	Q string `xml:"Q" json:"Q"`

	VERWENDUNGSZWECK1 string `xml:"VERWENDUNGSZWECK1" json:"VERWENDUNGSZWECK1"`

	VERWENDUNGSZWECK2 string `xml:"VERWENDUNGSZWECK2" json:"VERWENDUNGSZWECK2"`
}

type SearchOut struct {
	Return_ BedirectServerSearchResult `xml:"return" json:"return"`
}

type InformationIn struct {
	KID string `xml:"KID" json:"KID"`

	IDSTRING string `xml:"IDSTRING" json:"IDSTRING"`

	BIPID string `xml:"BIPID" json:"BIPID"`

	VERWENDUNGSZWECK1 string `xml:"VERWENDUNGSZWECK1" json:"VERWENDUNGSZWECK1"`

	VERWENDUNGSZWECK2 string `xml:"VERWENDUNGSZWECK2" json:"VERWENDUNGSZWECK2"`
}

type InformationOut struct {
	Return_ BedirectServerInformationResult `xml:"return" json:"return"`
}

type SoapServicePort interface {

	// search
	Search(ctx context.Context, request *SearchIn) (*SearchOut, error)

	// information
	Information(ctx context.Context, request *InformationIn) (*InformationOut, error)
}

type soapServicePort struct {
	client *soap.Client
}

func NewSoapServicePort(client *soap.Client) SoapServicePort {
	return &soapServicePort{
		client: client,
	}
}

func (service *soapServicePort) Search(ctx context.Context, request *SearchIn) (*SearchOut, error) {
	response := new(SearchOut)
	err := service.client.CallContext(ctx, "", request, response)
	if err != nil {
		return nil, err
	}
	return response, nil
}

func (service *soapServicePort) Information(ctx context.Context, request *InformationIn) (*InformationOut, error) {
	response := new(InformationOut)
	err := service.client.CallContext(ctx, "", request, response)
	if err != nil {
		return nil, err
	}
	return response, nil
}
