// Code generated by gowsdl DO NOT EDIT.

package godemo

import (
	"context"
	"encoding/xml"
	"github.com/enthus-golang/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type DatabaseEntry struct {
	ANFRAGEID *string `xml:"ANFRAGEID,omitempty" json:"ANFRAGEID,omitempty"`

	BIPID *string `xml:"BIPID,omitempty" json:"BIPID,omitempty"`

	FIRMENNAMENSZEILE1 *string `xml:"FIRMENNAMENSZEILE1,omitempty" json:"FIRMENNAMENSZEILE1,omitempty"`

	FIRMENNAMENSZEILE2 *string `xml:"FIRMENNAMENSZEILE2,omitempty" json:"FIRMENNAMENSZEILE2,omitempty"`

	FIRMENNAMENSZEILE3 *string `xml:"FIRMENNAMENSZEILE3,omitempty" json:"FIRMENNAMENSZEILE3,omitempty"`

	FIRMENNAME_GESAMT *string `xml:"FIRMENNAME_GESAMT,omitempty" json:"FIRMENNAME_GESAMT,omitempty"`

	STRASSE_GESAMT *string `xml:"STRASSE_GESAMT,omitempty" json:"STRASSE_GESAMT,omitempty"`

	PLZ *string `xml:"PLZ,omitempty" json:"PLZ,omitempty"`

	ORT *string `xml:"ORT,omitempty" json:"ORT,omitempty"`

	TELEFON_VORWAHL *string `xml:"TELEFON_VORWAHL,omitempty" json:"TELEFON_VORWAHL,omitempty"`

	TELEFON_RUFNUMMER *string `xml:"TELEFON_RUFNUMMER,omitempty" json:"TELEFON_RUFNUMMER,omitempty"`

	CRF *string `xml:"CRF,omitempty" json:"CRF,omitempty"`

	ZCRF *string `xml:"ZCRF,omitempty" json:"ZCRF,omitempty"`

	HISTORIEN_FLAG_TEXT *string `xml:"HISTORIEN_FLAG_TEXT,omitempty" json:"HISTORIEN_FLAG_TEXT,omitempty"`

	STATUS_TEXT *string `xml:"STATUS_TEXT,omitempty" json:"STATUS_TEXT,omitempty"`

	SCORE *string `xml:"SCORE,omitempty" json:"SCORE,omitempty"`

	VERWENDUNGSZWECK1 *string `xml:"VERWENDUNGSZWECK1,omitempty" json:"VERWENDUNGSZWECK1,omitempty"`

	VERWENDUNGSZWECK2 *string `xml:"VERWENDUNGSZWECK2,omitempty" json:"VERWENDUNGSZWECK2,omitempty"`
}

type ArrayOfDatabaseEntry struct {
	Item []*DatabaseEntry `xml:"item,omitempty" json:"item,omitempty"`
}

type BedirectServerSearchResult struct {
	DatabaseEntryArray *ArrayOfDatabaseEntry `xml:"databaseEntryArray,omitempty" json:"databaseEntryArray,omitempty"`

	Status *string `xml:"status,omitempty" json:"status,omitempty"`

	Time int32 `xml:"time,omitempty" json:"time,omitempty"`
}

type BedirectServerInformationResult struct {
	STATUS *string `xml:"STATUS,omitempty" json:"STATUS,omitempty"`

	ANFRAGEID *string `xml:"ANFRAGEID,omitempty" json:"ANFRAGEID,omitempty"`

	BIPID *string `xml:"BIPID,omitempty" json:"BIPID,omitempty"`

	CRF *string `xml:"CRF,omitempty" json:"CRF,omitempty"`

	ZCRF *string `xml:"ZCRF,omitempty" json:"ZCRF,omitempty"`

	FIRMENNAMENSZEILE1 *string `xml:"FIRMENNAMENSZEILE1,omitempty" json:"FIRMENNAMENSZEILE1,omitempty"`

	FIRMENNAMENSZEILE2 *string `xml:"FIRMENNAMENSZEILE2,omitempty" json:"FIRMENNAMENSZEILE2,omitempty"`

	FIRMENNAMENSZEILE3 *string `xml:"FIRMENNAMENSZEILE3,omitempty" json:"FIRMENNAMENSZEILE3,omitempty"`

	FIRMENNAME_GESAMT *string `xml:"FIRMENNAME_GESAMT,omitempty" json:"FIRMENNAME_GESAMT,omitempty"`

	STRASSE_GESAMT *string `xml:"STRASSE_GESAMT,omitempty" json:"STRASSE_GESAMT,omitempty"`

	STRASSE *string `xml:"STRASSE,omitempty" json:"STRASSE,omitempty"`

	HAUSNR *string `xml:"HAUSNR,omitempty" json:"HAUSNR,omitempty"`

	HAUSNRZUS *string `xml:"HAUSNRZUS,omitempty" json:"HAUSNRZUS,omitempty"`

	LKZ *string `xml:"LKZ,omitempty" json:"LKZ,omitempty"`

	PLZ *string `xml:"PLZ,omitempty" json:"PLZ,omitempty"`

	ORT *string `xml:"ORT,omitempty" json:"ORT,omitempty"`

	HISTORIENSAETZE *string `xml:"HISTORIENSAETZE,omitempty" json:"HISTORIENSAETZE,omitempty"`

	UMZUGSDATUM *string `xml:"UMZUGSDATUM,omitempty" json:"UMZUGSDATUM,omitempty"`

	STATUS_ID *string `xml:"STATUS_ID,omitempty" json:"STATUS_ID,omitempty"`

	STATUS_ID_TEXT *string `xml:"STATUS_ID_TEXT,omitempty" json:"STATUS_ID_TEXT,omitempty"`

	COMPLIANCE_DATUM *string `xml:"COMPLIANCE_DATUM,omitempty" json:"COMPLIANCE_DATUM,omitempty"`

	COMPLIANCE_QUELLE *string `xml:"COMPLIANCE_QUELLE,omitempty" json:"COMPLIANCE_QUELLE,omitempty"`

	COMPLIANCE_IDENT *string `xml:"COMPLIANCE_IDENT,omitempty" json:"COMPLIANCE_IDENT,omitempty"`

	TELEFON_VORWAHL *string `xml:"TELEFON_VORWAHL,omitempty" json:"TELEFON_VORWAHL,omitempty"`

	TELEFON_RUFNUMMER *string `xml:"TELEFON_RUFNUMMER,omitempty" json:"TELEFON_RUFNUMMER,omitempty"`

	FAX_VORWAHL *string `xml:"FAX_VORWAHL,omitempty" json:"FAX_VORWAHL,omitempty"`

	FAX_RUFNUMMER *string `xml:"FAX_RUFNUMMER,omitempty" json:"FAX_RUFNUMMER,omitempty"`

	EMAIL *string `xml:"EMAIL,omitempty" json:"EMAIL,omitempty"`

	URL *string `xml:"URL,omitempty" json:"URL,omitempty"`

	HR_TYP *string `xml:"HR_TYP,omitempty" json:"HR_TYP,omitempty"`

	HR_ORT *string `xml:"HR_ORT,omitempty" json:"HR_ORT,omitempty"`

	HR_NUMMER *string `xml:"HR_NUMMER,omitempty" json:"HR_NUMMER,omitempty"`

	HR_NUMMERZUS *string `xml:"HR_NUMMERZUS,omitempty" json:"HR_NUMMERZUS,omitempty"`

	UMSATZSTEUER_ID *string `xml:"UMSATZSTEUER_ID,omitempty" json:"UMSATZSTEUER_ID,omitempty"`

	STEUERNUMMER *string `xml:"STEUERNUMMER,omitempty" json:"STEUERNUMMER,omitempty"`

	STEUERNUMMER_ELSTER *string `xml:"STEUERNUMMER_ELSTER,omitempty" json:"STEUERNUMMER_ELSTER,omitempty"`

	AGS *string `xml:"AGS,omitempty" json:"AGS,omitempty"`

	GEOKOORDINATE_X *string `xml:"GEOKOORDINATE_X,omitempty" json:"GEOKOORDINATE_X,omitempty"`

	GEOKOORDINATE_Y *string `xml:"GEOKOORDINATE_Y,omitempty" json:"GEOKOORDINATE_Y,omitempty"`

	MITARBEITER_STAFFEL *string `xml:"MITARBEITER_STAFFEL,omitempty" json:"MITARBEITER_STAFFEL,omitempty"`

	MITARBEITER_STAFFEL_TEXT *string `xml:"MITARBEITER_STAFFEL_TEXT,omitempty" json:"MITARBEITER_STAFFEL_TEXT,omitempty"`

	MITARBEITER_REAL *string `xml:"MITARBEITER_REAL,omitempty" json:"MITARBEITER_REAL,omitempty"`

	KONZ_MITARBEITER_STAFFEL *string `xml:"KONZ_MITARBEITER_STAFFEL,omitempty" json:"KONZ_MITARBEITER_STAFFEL,omitempty"`

	KONZ_MITARBEITER_STAFFEL_TEXT *string `xml:"KONZ_MITARBEITER_STAFFEL_TEXT,omitempty" json:"KONZ_MITARBEITER_STAFFEL_TEXT,omitempty"`

	KONZ_MITARBEITER_REAL *string `xml:"KONZ_MITARBEITER_REAL,omitempty" json:"KONZ_MITARBEITER_REAL,omitempty"`

	BUEROPLATZ_STAFFEL *string `xml:"BUEROPLATZ_STAFFEL,omitempty" json:"BUEROPLATZ_STAFFEL,omitempty"`

	BUEROPLATZ_STAFFEL_TEXT *string `xml:"BUEROPLATZ_STAFFEL_TEXT,omitempty" json:"BUEROPLATZ_STAFFEL_TEXT,omitempty"`

	MITARBEITERENTWICKLUNG *string `xml:"MITARBEITERENTWICKLUNG,omitempty" json:"MITARBEITERENTWICKLUNG,omitempty"`

	UMSATZ_STAFFEL *string `xml:"UMSATZ_STAFFEL,omitempty" json:"UMSATZ_STAFFEL,omitempty"`

	UMSATZ_STAFFEL_TEXT *string `xml:"UMSATZ_STAFFEL_TEXT,omitempty" json:"UMSATZ_STAFFEL_TEXT,omitempty"`

	UMSATZ_REAL *string `xml:"UMSATZ_REAL,omitempty" json:"UMSATZ_REAL,omitempty"`

	KONZ_UMSATZ_STAFFEL *string `xml:"KONZ_UMSATZ_STAFFEL,omitempty" json:"KONZ_UMSATZ_STAFFEL,omitempty"`

	KONZ_UMSATZ_STAFFEL_TEXT *string `xml:"KONZ_UMSATZ_STAFFEL_TEXT,omitempty" json:"KONZ_UMSATZ_STAFFEL_TEXT,omitempty"`

	KONZ_UMSATZ_REAL *string `xml:"KONZ_UMSATZ_REAL,omitempty" json:"KONZ_UMSATZ_REAL,omitempty"`

	UMSATZENTWICKLUNG *string `xml:"UMSATZENTWICKLUNG,omitempty" json:"UMSATZENTWICKLUNG,omitempty"`

	KAPITAL_STAFFEL *string `xml:"KAPITAL_STAFFEL,omitempty" json:"KAPITAL_STAFFEL,omitempty"`

	KAPITAL_STAFFEL_TEXT *string `xml:"KAPITAL_STAFFEL_TEXT,omitempty" json:"KAPITAL_STAFFEL_TEXT,omitempty"`

	KAPITAL_REAL *string `xml:"KAPITAL_REAL,omitempty" json:"KAPITAL_REAL,omitempty"`

	RECHTSFORM_BD_ID *string `xml:"RECHTSFORM_BD_ID,omitempty" json:"RECHTSFORM_BD_ID,omitempty"`

	RECHTSFORM_BD_TEXT *string `xml:"RECHTSFORM_BD_TEXT,omitempty" json:"RECHTSFORM_BD_TEXT,omitempty"`

	RECHTSFORM_CRF *string `xml:"RECHTSFORM_CRF,omitempty" json:"RECHTSFORM_CRF,omitempty"`

	RECHTSFORM_CIS2 *string `xml:"RECHTSFORM_CIS2,omitempty" json:"RECHTSFORM_CIS2,omitempty"`

	RECHTSFORM_CIS2_TEXT *string `xml:"RECHTSFORM_CIS2_TEXT,omitempty" json:"RECHTSFORM_CIS2_TEXT,omitempty"`

	GRUENDUNGSDATUM *string `xml:"GRUENDUNGSDATUM,omitempty" json:"GRUENDUNGSDATUM,omitempty"`

	WZ_BRANCHE1 *string `xml:"WZ_BRANCHE1,omitempty" json:"WZ_BRANCHE1,omitempty"`

	WZ_BRANCHE1_TEXT *string `xml:"WZ_BRANCHE1_TEXT,omitempty" json:"WZ_BRANCHE1_TEXT,omitempty"`

	WZ_BRANCHE2 *string `xml:"WZ_BRANCHE2,omitempty" json:"WZ_BRANCHE2,omitempty"`

	WZ_BRANCHE2_TEXT *string `xml:"WZ_BRANCHE2_TEXT,omitempty" json:"WZ_BRANCHE2_TEXT,omitempty"`

	WZ_BRANCHE3 *string `xml:"WZ_BRANCHE3,omitempty" json:"WZ_BRANCHE3,omitempty"`

	WZ_BRANCHE3_TEXT *string `xml:"WZ_BRANCHE3_TEXT,omitempty" json:"WZ_BRANCHE3_TEXT,omitempty"`

	WZ_BRANCHE4 *string `xml:"WZ_BRANCHE4,omitempty" json:"WZ_BRANCHE4,omitempty"`

	WZ_BRANCHE4_TEXT *string `xml:"WZ_BRANCHE4_TEXT,omitempty" json:"WZ_BRANCHE4_TEXT,omitempty"`

	WZ_BRANCHE5 *string `xml:"WZ_BRANCHE5,omitempty" json:"WZ_BRANCHE5,omitempty"`

	WZ_BRANCHE5_TEXT *string `xml:"WZ_BRANCHE5_TEXT,omitempty" json:"WZ_BRANCHE5_TEXT,omitempty"`

	BD_BRANCHE1 *string `xml:"BD_BRANCHE1,omitempty" json:"BD_BRANCHE1,omitempty"`

	BD_BRANCHE1_TEXT *string `xml:"BD_BRANCHE1_TEXT,omitempty" json:"BD_BRANCHE1_TEXT,omitempty"`

	BD_BRANCHE2 *string `xml:"BD_BRANCHE2,omitempty" json:"BD_BRANCHE2,omitempty"`

	BD_BRANCHE2_TEXT *string `xml:"BD_BRANCHE2_TEXT,omitempty" json:"BD_BRANCHE2_TEXT,omitempty"`

	BD_BRANCHE3 *string `xml:"BD_BRANCHE3,omitempty" json:"BD_BRANCHE3,omitempty"`

	BD_BRANCHE3_TEXT *string `xml:"BD_BRANCHE3_TEXT,omitempty" json:"BD_BRANCHE3_TEXT,omitempty"`

	BD_BRANCHE4 *string `xml:"BD_BRANCHE4,omitempty" json:"BD_BRANCHE4,omitempty"`

	BD_BRANCHE4_TEXT *string `xml:"BD_BRANCHE4_TEXT,omitempty" json:"BD_BRANCHE4_TEXT,omitempty"`

	BD_BRANCHE5 *string `xml:"BD_BRANCHE5,omitempty" json:"BD_BRANCHE5,omitempty"`

	BD_BRANCHE5_TEXT *string `xml:"BD_BRANCHE5_TEXT,omitempty" json:"BD_BRANCHE5_TEXT,omitempty"`

	NACE1 *string `xml:"NACE1,omitempty" json:"NACE1,omitempty"`

	NACE1_TEXT *string `xml:"NACE1_TEXT,omitempty" json:"NACE1_TEXT,omitempty"`

	NACE2 *string `xml:"NACE2,omitempty" json:"NACE2,omitempty"`

	NACE2_TEXT *string `xml:"NACE2_TEXT,omitempty" json:"NACE2_TEXT,omitempty"`

	NACE3 *string `xml:"NACE3,omitempty" json:"NACE3,omitempty"`

	NACE3_TEXT *string `xml:"NACE3_TEXT,omitempty" json:"NACE3_TEXT,omitempty"`

	NACE4 *string `xml:"NACE4,omitempty" json:"NACE4,omitempty"`

	NACE4_TEXT *string `xml:"NACE4_TEXT,omitempty" json:"NACE4_TEXT,omitempty"`

	NACE5 *string `xml:"NACE5,omitempty" json:"NACE5,omitempty"`

	NACE5_TEXT *string `xml:"NACE5_TEXT,omitempty" json:"NACE5_TEXT,omitempty"`

	MARKE1 *string `xml:"MARKE1,omitempty" json:"MARKE1,omitempty"`

	MARKE1_TEXT *string `xml:"MARKE1_TEXT,omitempty" json:"MARKE1_TEXT,omitempty"`

	MARKE2 *string `xml:"MARKE2,omitempty" json:"MARKE2,omitempty"`

	MARKE2_TEXT *string `xml:"MARKE2_TEXT,omitempty" json:"MARKE2_TEXT,omitempty"`

	MARKE3 *string `xml:"MARKE3,omitempty" json:"MARKE3,omitempty"`

	MARKE3_TEXT *string `xml:"MARKE3_TEXT,omitempty" json:"MARKE3_TEXT,omitempty"`

	MARKE4 *string `xml:"MARKE4,omitempty" json:"MARKE4,omitempty"`

	MARKE4_TEXT *string `xml:"MARKE4_TEXT,omitempty" json:"MARKE4_TEXT,omitempty"`

	MARKE5 *string `xml:"MARKE5,omitempty" json:"MARKE5,omitempty"`

	MARKE5_TEXT *string `xml:"MARKE5_TEXT,omitempty" json:"MARKE5_TEXT,omitempty"`

	BIPID_DIREKTE_MUTTER *string `xml:"BIPID_DIREKTE_MUTTER,omitempty" json:"BIPID_DIREKTE_MUTTER,omitempty"`

	FIRMENNAME_DIREKTE_MUTTER *string `xml:"FIRMENNAME_DIREKTE_MUTTER,omitempty" json:"FIRMENNAME_DIREKTE_MUTTER,omitempty"`

	BIPID_HOECHSTE_MUTTER *string `xml:"BIPID_HOECHSTE_MUTTER,omitempty" json:"BIPID_HOECHSTE_MUTTER,omitempty"`

	FIRMENNAME_HOECHSTE_MUTTER *string `xml:"FIRMENNAME_HOECHSTE_MUTTER,omitempty" json:"FIRMENNAME_HOECHSTE_MUTTER,omitempty"`

	VERBINDUNG_MUTTER *string `xml:"VERBINDUNG_MUTTER,omitempty" json:"VERBINDUNG_MUTTER,omitempty"`

	VERBINDUNG_TOCHTER *string `xml:"VERBINDUNG_TOCHTER,omitempty" json:"VERBINDUNG_TOCHTER,omitempty"`

	VERBINDUNG_ZENTRALE *string `xml:"VERBINDUNG_ZENTRALE,omitempty" json:"VERBINDUNG_ZENTRALE,omitempty"`

	VERBINDUNG_NDL *string `xml:"VERBINDUNG_NDL,omitempty" json:"VERBINDUNG_NDL,omitempty"`

	BIPID_PER *string `xml:"BIPID_PER,omitempty" json:"BIPID_PER,omitempty"`

	CRF_PER *string `xml:"CRF_PER,omitempty" json:"CRF_PER,omitempty"`

	ANREDE_PERSON *string `xml:"ANREDE_PERSON,omitempty" json:"ANREDE_PERSON,omitempty"`

	ADELSTITEL *string `xml:"ADELSTITEL,omitempty" json:"ADELSTITEL,omitempty"`

	AKADEMISCHERTITEL *string `xml:"AKADEMISCHERTITEL,omitempty" json:"AKADEMISCHERTITEL,omitempty"`

	VORNAME *string `xml:"VORNAME,omitempty" json:"VORNAME,omitempty"`

	NAMENSPREFIX *string `xml:"NAMENSPREFIX,omitempty" json:"NAMENSPREFIX,omitempty"`

	NACHNAME *string `xml:"NACHNAME,omitempty" json:"NACHNAME,omitempty"`

	NAMENSSUFFIX *string `xml:"NAMENSSUFFIX,omitempty" json:"NAMENSSUFFIX,omitempty"`

	FUNKTIONSSCHLUESSEL1 *string `xml:"FUNKTIONSSCHLUESSEL1,omitempty" json:"FUNKTIONSSCHLUESSEL1,omitempty"`

	FUNKTION1_TEXT *string `xml:"FUNKTION1_TEXT,omitempty" json:"FUNKTION1_TEXT,omitempty"`

	FUNKTIONSSCHLUESSEL2 *string `xml:"FUNKTIONSSCHLUESSEL2,omitempty" json:"FUNKTIONSSCHLUESSEL2,omitempty"`

	FUNKTION2_TEXT *string `xml:"FUNKTION2_TEXT,omitempty" json:"FUNKTION2_TEXT,omitempty"`

	FUNKTIONSSCHLUESSEL3 *string `xml:"FUNKTIONSSCHLUESSEL3,omitempty" json:"FUNKTIONSSCHLUESSEL3,omitempty"`

	FUNKTION3_TEXT *string `xml:"FUNKTION3_TEXT,omitempty" json:"FUNKTION3_TEXT,omitempty"`

	FUNKTIONSSCHLUESSEL4 *string `xml:"FUNKTIONSSCHLUESSEL4,omitempty" json:"FUNKTIONSSCHLUESSEL4,omitempty"`

	FUNKTION4_TEXT *string `xml:"FUNKTION4_TEXT,omitempty" json:"FUNKTION4_TEXT,omitempty"`

	FUNKTIONSSCHLUESSEL5 *string `xml:"FUNKTIONSSCHLUESSEL5,omitempty" json:"FUNKTIONSSCHLUESSEL5,omitempty"`

	FUNKTION5_TEXT *string `xml:"FUNKTION5_TEXT,omitempty" json:"FUNKTION5_TEXT,omitempty"`

	FUNKTIONSSCHLUESSEL6 *string `xml:"FUNKTIONSSCHLUESSEL6,omitempty" json:"FUNKTIONSSCHLUESSEL6,omitempty"`

	FUNKTION6_TEXT *string `xml:"FUNKTION6_TEXT,omitempty" json:"FUNKTION6_TEXT,omitempty"`

	BRIEFANREDE *string `xml:"BRIEFANREDE,omitempty" json:"BRIEFANREDE,omitempty"`

	FIRMA_SELECT *string `xml:"FIRMA_SELECT,omitempty" json:"FIRMA_SELECT,omitempty"`

	TELEFON_SELECT *string `xml:"TELEFON_SELECT,omitempty" json:"TELEFON_SELECT,omitempty"`

	BLZ1 *string `xml:"BLZ1,omitempty" json:"BLZ1,omitempty"`

	BANKNAME1_TEXT *string `xml:"BANKNAME1_TEXT,omitempty" json:"BANKNAME1_TEXT,omitempty"`

	BLZ2 *string `xml:"BLZ2,omitempty" json:"BLZ2,omitempty"`

	BANKNAME2_TEXT *string `xml:"BANKNAME2_TEXT,omitempty" json:"BANKNAME2_TEXT,omitempty"`

	BLZ3 *string `xml:"BLZ3,omitempty" json:"BLZ3,omitempty"`

	BANKNAME3_TEXT *string `xml:"BANKNAME3_TEXT,omitempty" json:"BANKNAME3_TEXT,omitempty"`

	BLZ4 *string `xml:"BLZ4,omitempty" json:"BLZ4,omitempty"`

	BANKNAME4_TEXT *string `xml:"BANKNAME4_TEXT,omitempty" json:"BANKNAME4_TEXT,omitempty"`

	BLZ5 *string `xml:"BLZ5,omitempty" json:"BLZ5,omitempty"`

	BANKNAME5_TEXT *string `xml:"BANKNAME5_TEXT,omitempty" json:"BANKNAME5_TEXT,omitempty"`

	BLZ6 *string `xml:"BLZ6,omitempty" json:"BLZ6,omitempty"`

	BANKNAME6_TEXT *string `xml:"BANKNAME6_TEXT,omitempty" json:"BANKNAME6_TEXT,omitempty"`

	NACE1_ABT *string `xml:"NACE1_ABT,omitempty" json:"NACE1_ABT,omitempty"`

	NACE1_ABT_TEXT *string `xml:"NACE1_ABT_TEXT,omitempty" json:"NACE1_ABT_TEXT,omitempty"`

	NACE2_ABT *string `xml:"NACE2_ABT,omitempty" json:"NACE2_ABT,omitempty"`

	NACE2_ABT_TEXT *string `xml:"NACE2_ABT_TEXT,omitempty" json:"NACE2_ABT_TEXT,omitempty"`

	NACE3_ABT *string `xml:"NACE3_ABT,omitempty" json:"NACE3_ABT,omitempty"`

	NACE3_ABT_TEXT *string `xml:"NACE3_ABT_TEXT,omitempty" json:"NACE3_ABT_TEXT,omitempty"`

	NACE4_ABT *string `xml:"NACE4_ABT,omitempty" json:"NACE4_ABT,omitempty"`

	NACE4_ABT_TEXT *string `xml:"NACE4_ABT_TEXT,omitempty" json:"NACE4_ABT_TEXT,omitempty"`

	NACE5_ABT *string `xml:"NACE5_ABT,omitempty" json:"NACE5_ABT,omitempty"`

	NACE5_ABT_TEXT *string `xml:"NACE5_ABT_TEXT,omitempty" json:"NACE5_ABT_TEXT,omitempty"`

	SOCIALMEDIA1 *string `xml:"SOCIALMEDIA1,omitempty" json:"SOCIALMEDIA1,omitempty"`

	SOCIALMEDIA2 *string `xml:"SOCIALMEDIA2,omitempty" json:"SOCIALMEDIA2,omitempty"`

	SOCIALMEDIA3 *string `xml:"SOCIALMEDIA3,omitempty" json:"SOCIALMEDIA3,omitempty"`

	SOCIALMEDIA4 *string `xml:"SOCIALMEDIA4,omitempty" json:"SOCIALMEDIA4,omitempty"`

	SOCIALMEDIA5 *string `xml:"SOCIALMEDIA5,omitempty" json:"SOCIALMEDIA5,omitempty"`

	SOCIALMEDIA6 *string `xml:"SOCIALMEDIA6,omitempty" json:"SOCIALMEDIA6,omitempty"`

	SOCIALMEDIA7 *string `xml:"SOCIALMEDIA7,omitempty" json:"SOCIALMEDIA7,omitempty"`

	SOCIALMEDIA8 *string `xml:"SOCIALMEDIA8,omitempty" json:"SOCIALMEDIA8,omitempty"`

	SOCIALMEDIA9 *string `xml:"SOCIALMEDIA9,omitempty" json:"SOCIALMEDIA9,omitempty"`

	SOCIALMEDIA10 *string `xml:"SOCIALMEDIA10,omitempty" json:"SOCIALMEDIA10,omitempty"`

	TAGBEVOELKERUNG *string `xml:"TAGBEVOELKERUNG,omitempty" json:"TAGBEVOELKERUNG,omitempty"`

	SOHO *string `xml:"SOHO,omitempty" json:"SOHO,omitempty"`

	FELD1 *string `xml:"FELD1,omitempty" json:"FELD1,omitempty"`

	FELD2 *string `xml:"FELD2,omitempty" json:"FELD2,omitempty"`

	FELD3 *string `xml:"FELD3,omitempty" json:"FELD3,omitempty"`

	FELD4 *string `xml:"FELD4,omitempty" json:"FELD4,omitempty"`

	FELD5 *string `xml:"FELD5,omitempty" json:"FELD5,omitempty"`

	VERWENDUNGSZWECK1 *string `xml:"VERWENDUNGSZWECK1,omitempty" json:"VERWENDUNGSZWECK1,omitempty"`

	VERWENDUNGSZWECK2 *string `xml:"VERWENDUNGSZWECK2,omitempty" json:"VERWENDUNGSZWECK2,omitempty"`
}

type SearchIn struct {
	KID string `xml:"KID" json:"KID"`

	IDSTRING string `xml:"IDSTRING" json:"IDSTRING"`

	FIRMENNAME_GESAMT string `xml:"FIRMENNAME_GESAMT" json:"FIRMENNAME_GESAMT"`

	ORT string `xml:"ORT" json:"ORT"`

	PLZ string `xml:"PLZ" json:"PLZ"`

	STRASSE_GESAMT string `xml:"STRASSE_GESAMT" json:"STRASSE_GESAMT"`

	TELEFON_VORWAHL string `xml:"TELEFON_VORWAHL" json:"TELEFON_VORWAHL"`

	TELEFON_RUFNUMMER string `xml:"TELEFON_RUFNUMMER" json:"TELEFON_RUFNUMMER"`

	EMAIL string `xml:"EMAIL" json:"EMAIL"`

	URL string `xml:"URL" json:"URL"`

	VERSION string `xml:"VERSION" json:"VERSION"`

	HR_NUMMER string `xml:"HR_NUMMER" json:"HR_NUMMER"`

	HR_ORT string `xml:"HR_ORT" json:"HR_ORT"`

	HR_TYP string `xml:"HR_TYP" json:"HR_TYP"`

	CRF string `xml:"CRF" json:"CRF"`

	ZCRF string `xml:"ZCRF" json:"ZCRF"`

	RECHTSFORM_BD_TEXT string `xml:"RECHTSFORM_BD_TEXT" json:"RECHTSFORM_BD_TEXT"`

	PRIMAERBRANCHE string `xml:"PRIMAERBRANCHE" json:"PRIMAERBRANCHE"`

	SEKUNDAERBRANCHE string `xml:"SEKUNDAERBRANCHE" json:"SEKUNDAERBRANCHE"`

	MARKENBRANCHE string `xml:"MARKENBRANCHE" json:"MARKENBRANCHE"`

	PERSON string `xml:"PERSON" json:"PERSON"`

	ID string `xml:"ID" json:"ID"`

	UMSATZSTEUER_ID string `xml:"UMSATZSTEUER_ID" json:"UMSATZSTEUER_ID"`

	STEUERNUMMER string `xml:"STEUERNUMMER" json:"STEUERNUMMER"`

	STEUERNUMMER_ELSTER string `xml:"STEUERNUMMER_ELSTER" json:"STEUERNUMMER_ELSTER"`

	HANDELSNAME string `xml:"HANDELSNAME" json:"HANDELSNAME"`

	Q string `xml:"Q" json:"Q"`

	VERWENDUNGSZWECK1 string `xml:"VERWENDUNGSZWECK1" json:"VERWENDUNGSZWECK1"`

	VERWENDUNGSZWECK2 string `xml:"VERWENDUNGSZWECK2" json:"VERWENDUNGSZWECK2"`
}

type SearchOut struct {
	Result BedirectServerSearchResult `xml:"return" json:"return"`
}

type InformationIn struct {
	KID string `xml:"KID" json:"KID"`

	IDSTRING string `xml:"IDSTRING" json:"IDSTRING"`

	BIPID string `xml:"BIPID" json:"BIPID"`

	VERWENDUNGSZWECK1 string `xml:"VERWENDUNGSZWECK1" json:"VERWENDUNGSZWECK1"`

	VERWENDUNGSZWECK2 string `xml:"VERWENDUNGSZWECK2" json:"VERWENDUNGSZWECK2"`
}

type InformationOut struct {
	Result BedirectServerInformationResult `xml:"return" json:"return"`
}

type SoapServicePort interface {

	// search
	Search(ctx context.Context, request *SearchIn) (*SearchOut, error)

	// information
	Information(ctx context.Context, request *InformationIn) (*InformationOut, error)
}

type soapServicePort struct {
	client *soap.Client
}

func NewSoapServicePort(client *soap.Client) SoapServicePort {
	return &soapServicePort{
		client: client,
	}
}

func (service *soapServicePort) Search(ctx context.Context, request *SearchIn) (*SearchOut, error) {
	response := new(SearchOut)
	err := service.client.CallContext(ctx, "", request, response)
	if err != nil {
		return nil, err
	}
	return response, nil
}

func (service *soapServicePort) Information(ctx context.Context, request *InformationIn) (*InformationOut, error) {
	response := new(InformationOut)
	err := service.client.CallContext(ctx, "", request, response)
	if err != nil {
		return nil, err
	}
	return response, nil
}
