// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

package main

import (
	"encoding/xml"
	"fmt"
)

// These types would be generated by gowsdl from WSDL with inline complex types

// OrderType represents an order with optional shipping address
type OrderType struct {
	OrderId         string                        `xml:"orderId,omitempty"`
	ShippingAddress *OrderTypeShippingAddressType `xml:"shippingAddress,omitempty"`
	BillingAddress  OrderTypeBillingAddressType  `xml:"billingAddress,omitempty"`
	Items           []OrderTypeItemsType          `xml:"items,omitempty"`
}

// OrderTypeShippingAddressType is a named type generated for the inline shippingAddress complex type
type OrderTypeShippingAddressType struct {
	Street  string `xml:"street,omitempty"`
	City    string `xml:"city,omitempty"`
	ZipCode string `xml:"zipCode,omitempty"`
}

// OrderTypeBillingAddressType is a named type generated for the inline billingAddress complex type
type OrderTypeBillingAddressType struct {
	Street string `xml:"street,omitempty"`
	City   string `xml:"city,omitempty"`
}

// OrderTypeItemsType is a named type generated for the inline items complex type
type OrderTypeItemsType struct {
	ItemId   string `xml:"itemId,omitempty"`
	Quantity int    `xml:"quantity,omitempty"`
}

func main() {
	// Example 1: Creating an order with optional shipping address
	order1 := &OrderType{
		OrderId: "12345",
		ShippingAddress: &OrderTypeShippingAddressType{
			Street:  "123 Main St",
			City:    "New York",
			ZipCode: "10001",
		},
		BillingAddress: OrderTypeBillingAddressType{
			Street: "456 Billing Ave",
			City:   "Boston",
		},
		Items: []OrderTypeItemsType{
			{ItemId: "ITEM001", Quantity: 2},
			{ItemId: "ITEM002", Quantity: 1},
		},
	}

	// Marshal to XML
	xmlData, err := xml.MarshalIndent(order1, "", "  ")
	if err != nil {
		panic(err)
	}
	fmt.Println("Order with shipping address:")
	fmt.Println(string(xmlData))
	fmt.Println()

	// Example 2: Creating an order without optional shipping address
	order2 := &OrderType{
		OrderId: "12346",
		// ShippingAddress is nil, will be omitted from XML
		BillingAddress: OrderTypeBillingAddressType{
			Street: "789 Customer Rd",
			City:   "Chicago",
		},
		Items: []OrderTypeItemsType{
			{ItemId: "ITEM003", Quantity: 5},
		},
	}

	xmlData2, err := xml.MarshalIndent(order2, "", "  ")
	if err != nil {
		panic(err)
	}
	fmt.Println("Order without shipping address (omitted from XML):")
	fmt.Println(string(xmlData2))
	fmt.Println()

	// Example 3: Safely accessing optional fields
	processOrder := func(order *OrderType) {
		fmt.Printf("Processing order %s\n", order.OrderId)
		
		// Safe nil check for optional field
		if order.ShippingAddress != nil {
			fmt.Printf("  Ship to: %s, %s %s\n", 
				order.ShippingAddress.Street,
				order.ShippingAddress.City,
				order.ShippingAddress.ZipCode)
		} else {
			fmt.Println("  No shipping address (pickup order)")
		}
		
		fmt.Printf("  Bill to: %s, %s\n", 
			order.BillingAddress.Street,
			order.BillingAddress.City)
		
		fmt.Printf("  Items: %d\n", len(order.Items))
		for _, item := range order.Items {
			fmt.Printf("    - %s (qty: %d)\n", item.ItemId, item.Quantity)
		}
		fmt.Println()
	}

	processOrder(order1)
	processOrder(order2)
}